version: 0.0.{build}

image: Visual Studio 2017

test: off

build:
  publish_nuget: true

build_script:
  - ps: gitversion /output buildserver
  - ps: nuget pack -Version $env:GitVersion_NuGetVersionV2 -properties "branch=$env:GitVersion_BranchName;commit=$env:GitVersion_Sha"

artifacts:
  - path: "*.nupkg"

for:
  - branches:
      only:
        - master

    deploy:
      - provider: NuGet
        api_key:
          secure: GMc0xUTASI8qTPK1/eN/GFs6PBhPFBin1TT1hE5N8NlkU7VSBx3z4zQinSv/ICmx
        artifact: /.*\.nupkg/
